### ISSUE TITLE
Feedback on proposal

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Income-Predictors-for-US-Adults#4]
@Gopsathvik and @danielglin, you have chosen an interesting topic and I look forward to reading more about your analysis! Here are some improvement points and minor suggestions.

**Reasoning:**
- You have not mentioned any particular question for your analysis. You have a predictive analysis at hand, but what is your motivation to do this analysis? Do you want to find out which features are the most important in predicting income level? Do you want to find out what what level of income a person would have given their age and gender? Are you trying to build a model that has a certain level of accuracy? In short, what is the _question_ are you trying to address? You can refer to the issue Tiffany has created in the students repo [here](https://github.ubc.ca/MDS-2018-19/DSCI_522_dsci-workflows_students/issues/9) for more information on this point.
- I believe you can briefly mention why you chose a decision tree in your analysis. Why do you think this model suitable for your analysis?

**Mechanics:**
- The title of your repository should be a meaningful name reflecting the project. Try to come up with a name for your project and change the repository name to that. You can keep DSCI_522 but I would personally suggest leaving it out. Once you edit the title of the repository, don't forget to also change the title of the readme.
- I realized that you mention certain folders and/or files in the readme. When you point the reader to a specific file or folder within the repository, make sure to add links to these.
- You have an `src` as well as an `analysis` folder. The `analysis` folder is redundant since you have the `src` folder. If there is a logic to it that I am not aware, please let me know.
- You can make improvements on the structure of the main readme. Keep in mind that this is the landing page for your project. So you can have an introduction paragraph explaining the problem at hand and your motivation for the analysis, the source and the characteristics of the data, and what sorts of results you expect in more detail.
- Your code shows that you can read the data into your environment. It could also be helpful if you showed the first few rows or a basic exploratory visualization on the main readme.

**Minor suggestions**
- Try to use imperative mood in your commit messages. [Here](https://chris.beams.io/posts/git-commit/) is a great source to improve your commit messages.
- You can elaborate more on how you would communicate and visualize your results.

**Comment by Gopsathvik** [comment]
Review incorporated
